---
title: "Schedule HT22"
output:
  html_document:
    self_contained: true
    toc: false
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

Note that the *Handledning* (lecture/tutorial) starts at **09:30**! 
On Mondays you will have your peer review assigned, please do that the first hour. On Thursdays, you will either need to work with resubmissions of your hand in or by yourself.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(jsonlite))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(knitr))

# Byt https mot aktuell schemalänk nedan
TimeEdit_URL <- "https://cloud.timeedit.net/su/web/stud1/ri107655X99Z06Q6Z96g0Y75y5066Y35Q01gQY6Q55737.json"
datum <- unique(fromJSON(TimeEdit_URL, flatten = TRUE)$reservations) %>% 
    mutate(veckodag = weekdays(as.Date(startdate)), 
           tid = paste(starttime, endtime, sep = "-")) %>% 
    select(veckodag, startdate, tid) %>% 
    distinct() %>%
  filter(startdate>=ymd("2022-11-07"))
topics <- c(
    "[**Introduction. Software, GitHub and Markdown.**](class_instructions/day1.html) [[Lecture Slides](slides/slide1.html)],  _We start at 9am. Handledning starts as soon as lecture is done._",
    "[**Tidyverse, Basic dplyr and ggplot2**](class_instructions/day2.html). [[Lecture Slides](slides/slide2.html)], We start at 9am. Handledning starts as soon as lecture is done.",
    "[**Tidyverse: group_by and summarise, more ggplot2.**](class_instructions/day3.html), Peer review 08:45-09:30, handledning 09:30-11:30",
    "[**Exploratory data analysis.**](class_instructions/day4.html), handledning 09:30-11:30",
    "[**Cleaning data: Tidy data. Long to wide and back.**](class_instructions/day5.html), Peer review 08:45-09:30, handledning 09:30-11:30",
    "[**Relational data: Combining tables with dplyr joins.**](class_instructions/day6.html), handledning 09:30-11:30",
    "[**Relational data: SQL basics.**](class_instructions/day7.html), Peer review 08:45-09:30, handledning 09:30-11:30",
    "**Guest lecture: TBA**,  Resubmission and handledning starts after lecture." ,
    "**Text data: Regular expressions.**, Peer review 08:45-09:30, handledning 09:30-11:30",
    "**Using APIs: httr, JSON and XML.**, handledning 09:30-11:30",
    "**R programming: Functional programming, aka functions!**, Peer review 08:45-09:30, handledning 09:30-11:30",
    "**R Programming: Functional programming with purrr.**, handledning 09:30-11:30",
    "**Web-scraping: Basic rvest.**, Peer review 08:45-09:30, handledning 09:30-11:30",
    "Zoom meeting with option for questions in preparation for exam! Work on resubmission of HW6 and project!",
    "Exam",
    "Project presentation.")

# topics <- c(
#     "[**Lecture**: Introduction. Software, GitHub and Markdown.](class_instructions/day1.html) [[Slides](slides/slide1.html)],  _We start at 9am. Handledning starts as soon as lecture is done._",
#     "[**Lecture**: Tidyverse, Basic dplyr and ggplot2.](class_instructions/day2.html) [[Slides](slides/slide2.html)] [[Video](https://video.su.se/media/Dag%202%20-%20readr%2C%20dplyr%2C%20pipes%20%26%20ggplot/0_e7cf1v9a)], _We start at 9am. Handledning starts as soon as lecture is done._",
#     "[Tidyverse: group_by and summarise, more ggplot2.](class_instructions/day3.html), Peer review 08:45-09:30, handledning 09:30-11:30",
#     "[Exploratory data analysis](class_instructions/day4.html), handledning 09:30-11:30",
#     "[Cleaning data: Tidy data. Long to wide and back.](class_instructions/day5.html), Peer review 08:45-09:30, handledning 09:30-11:30",
#     "[Relational data: Combining tables with dplyr joins.](class_instructions/day6.html), handledning 09:30-11:30",
#     "[Relational data: SQL basics](class_instructions/day7.html), Peer review 08:45-09:30, handledning 09:30-11:30",
#     # "**Guest Lecture** 08:45: Jan Alexandersson, Quantitative analyst, Abios, will do a lecture on principles of visualisation. [[Slides](slides/slide14.html)], _Resubmission and handledning starts after lecture. There are no lecture notes today!_",
#     "**Guest lecture: TBA**,  Resubmission and handledning starts after lecture." ,
#     "[Text data: Regular expressions.](class_instructions/day9.html), Peer review 08:45-09:30, handledning 09:30-11:30",
#     "[Using APIs: httr, JSON and XML.](class_instructions/day10.html), handledning 09:30-11:30",
#     "[R programming: Functional programming, aka functions!](class_instructions/day11.html), Peer review 08:45-09:30, handledning 09:30-11:30",
#     "[R Programming: Functional programming with purrr.](class_instructions/day12.html), handledning 09:30-11:30",
#     "[Web-scraping: Basic rvest.](class_instructions/day13.html), Peer review 08:45-09:30, handledning 09:30-11:30",
#     "Zoom meeting with option for questions in preparation for exam! Resubmission of HW6 and project work.",
#     "Exam",
#     "Project presentation.")

##
##Remove all links from topics. 
##@param topics Vector of characters containing the lecture info
##@param from_lecture_number First lecture number to remove URLs from.
##
remove_url_from_topics <- function(topics, from_lecture_number=1) {
    stopifnot(from_lecture_number>0)
    
    result <- stringr::str_replace(topics[from_lecture_number:length(topics)], "\\([^)]*\\)", "")
    result <- stringr::str_replace(result, "\\[([^)]*)\\]", "\\1")
    
    return(c(topics[seq_len(from_lecture_number-1)], result))
}

##Remove URLs. Increment this for every lecture we do.
from_lecture_number <- 14#length(topics) 
topics <- remove_url_from_topics(topics, from_lecture_number=from_lecture_number)
```

```{r TIMEEDIT, echo = FALSE, message=FALSE, warning=FALSE, results="asis"}
cat(paste0("<p>The schedule of the MT4007 HT22 course is automatically fetched from [TimeEdit](",stringr::str_replace(TimeEdit_URL,"\\.json",""),").<br><br></p>"))
```
```{r KABLESCHEDULE, echo = FALSE}
tibble(Lecture = seq_len(length(topics)), 
       Day = paste(datum$veckodag, datum$startdate, sep = ", "),
       Time = datum$tid, Topic = topics) %>%
kable()
```
